apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: influx_image
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: telegraf
        volumeMounts:
        - name: telegraf-pv
          mountPath: /var/lib/influxdb
        - name: influxdb
          mountPath: /etc/influxdb/influxdb.conf
          subPath: influxdb.conf
          readOnly: true
      volumes:
      - name: telegraf-pv
        persistentVolumeClaim:
          claimName: telegraf-pvc
      - name: influxdb
        configMap:
          name: influxdb
