apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.99.101-192.168.99.200
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb
  labels:
    app: influxdb
data:
  influxdb.conf: |
    bind-adress="127.0.0.1:8088"
    [meta]
      dir="/var/lib/influxdb/meta"
    [data]
      dir="/var/lib/influxdb/data"
      wal-dir = "/var/lib/influxdb/wal"
      trace-logging-enable=true
    [http]
      bind-addres=":8086"
      log-enabled=true
    [[graphite]]
      database="telegraf"
