apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-storage
  labels:
    app: mysql
    type: local
spec:
  capacity:
    storage: 100Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: "var/lib/data"
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: mysql-persistent-storage
#spec:
#  capacity:
#    storage: 50Mi
#  volumeMode: Filesystem
#  accessModes:
#    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Recycle
#  nfs:
#    path: /var/lib/mysql
#    server: 192.168.99.101
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: pv-influx
# spec:
#   capacity:
#     storage: 100Mi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Recycle
#   nfs:
#     path: /var/lib/mysql
#     server: 172.17.0.2
