apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.101
  selector:
    app: phpmyadmin
  ports:
    - port: 5000
      name: http
      protocol: TCP
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: php_image
        imagePullPolicy: Never
        ports:
        - containerPort: 5000