apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  annotations:
    metallb.universe.tf/allow-shared-ip: minikube
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.101
  selector:
    app: ftps
  ports:
    - port: 21
      name: https
      protocol: TCP
      targetPort: 21
    - name: port-passv
      protocol: TCP
      port: 10100
      targetPort: 10100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
        - image: ftps_image
          name: ftps
          imagePullPolicy: Never
          ports:
            - containerPort: 21
            - containerPort: 20
            - containerPort: 10100
