apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  annotations:
    metallb.universe.tf/allow-shared-ip: lol
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  selector:
    app: wordpress
  ports:
    - port: 5050
      name: https
      protocol: TCP
      targetPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - image: wordpress_image
          name: wordpress
          imagePullPolicy: Never
          ports:
            - containerPort: 5050
